# Generated by Django 2.2.7 on 2020-06-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workload',
            name='task',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='任务'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='assignee',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='标注员'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='lastid',
            field=models.IntegerField(blank=True, null=True, verbose_name='最后id'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='workcount',
            field=models.IntegerField(blank=True, null=True, verbose_name='工作量'),
        ),
    ]
