# Generated by Django 2.2.7 on 2020-06-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0002_auto_20200612_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workload',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
    ]
