# Generated by Django 2.2.7 on 2020-06-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0003_auto_20200616_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='workload',
            name='project_detail_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='项目全名'),
        ),
    ]
