# Generated by Django 2.2.7 on 2020-06-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0004_workload_project_detail_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workload',
            name='project_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='项目id'),
        ),
    ]
