# Generated by Django 2.2.7 on 2020-08-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0005_workload_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workload',
            name='pointscount',
            field=models.IntegerField(blank=True, null=True, verbose_name='点数量'),
        ),
    ]
