# Generated by Django 2.2.7 on 2020-10-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0006_workload_pointscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workload',
            name='lastid',
            field=models.IntegerField(blank=True, null=True, verbose_name='最后一个查询记录'),
        ),
    ]
