# Generated by Django 2.2.7 on 2020-02-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('workcount', models.IntegerField(blank=True, null=True)),
                ('lastid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workload',
            },
        ),
    ]
