version: "3"
services:
  db:
    container_name: aidsp_db
    image: postgres
    hostname: db
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

  web:
    container_name: aidsp_web
    image: aidsp
    restart: always
    build: .  
    command: "python3 manage.py runserver 0.0.0.0:8000 --insecure"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db