version: "3"
services:
  db:
    container_name: aidsp_db
    image: postgres
    hostname: db
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

  web:
    container_name: aidsp_web
    image: aidsp
    restart: always
    build: .  
    command: "python3 manage.py runserver 0.0.0.0:8000 --insecure"
    volumes:
      - .:/code
    depends_on:
      - db

  aidsp_proxy:
    container_name: aidsp_proxy
    image: nginx:stable-alpine
    restart: always
    environment:
      AIDSP_HOST: localhost
    depends_on:
      - web
    ports:
      - "8000:80"
    volumes:
      - ./aidsp_proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./aidsp_proxy/conf.d/aidsp.conf.template:/etc/nginx/conf.d/aidsp.conf.template:ro
    command: /bin/sh -c "envsubst '$$AIDSP_HOST' < /etc/nginx/conf.d/aidsp.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"