# Generated by Django 3.0.2 on 2020-02-02 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '需求文档'), (1, '采集文档'), (2, '标注文档')], verbose_name='文档类型')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='文档内容')),
                ('old_content', models.TextField(verbose_name='文档内容历史版本')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='标签名')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=50, unique=True, verbose_name='项目id')),
                ('project_name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('status', models.CharField(max_length=20, verbose_name='状态')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('background', models.TextField(help_text='填写此项目的需求背景，必须是markdown格式', verbose_name='项目背景')),
                ('total_demand', models.PositiveIntegerField(verbose_name='需求总量')),
                ('total_describe', models.CharField(max_length=200, verbose_name='需求数量描述')),
                ('deadline', models.DateTimeField(verbose_name='截止渐渐')),
                ('documents', models.ManyToManyField(related_name='document_project', to='aidsp.Document', verbose_name='文档')),
                ('labels', models.ManyToManyField(related_name='labels', to='aidsp.Label', verbose_name='标签')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='姓名')),
                ('username', models.CharField(max_length=10, verbose_name='用户名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('position', models.PositiveIntegerField(choices=[(0, '算法工程师'), (1, '生产管理员'), (2, '标注员')], verbose_name='职位')),
                ('current_task', models.IntegerField(verbose_name='当前任务')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('task_name', models.CharField(max_length=20, unique=True, verbose_name='任务名称')),
                ('task_link', models.URLField(verbose_name='任务链接')),
                ('begin_time', models.DateTimeField(verbose_name='开始时间')),
                ('done_time', models.DateTimeField(verbose_name='完成时间')),
                ('time_label', models.DateTimeField(verbose_name='时间标记点')),
                ('used_time', models.DateTimeField(verbose_name='任务用时')),
                ('total_time', models.DateTimeField(verbose_name='任务历时')),
                ('gross', models.IntegerField(verbose_name='此任务工作总量')),
                ('quantity_available', models.IntegerField(verbose_name='此任务有效工作量')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '未开始'), (1, '正在进行'), (2, '完成'), (3, '通过'), (4, '未通过')], verbose_name='状态')),
                ('number_of_reviews', models.PositiveSmallIntegerField(default=0, verbose_name='审核次数')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignee_task', to='aidsp.User', to_field='name', verbose_name='标注员')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_task', to='aidsp.Project', to_field='project_id', verbose_name='所属项目')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewer_task', to='aidsp.User', to_field='name', verbose_name='审核员')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.IntegerField(verbose_name='图片序号')),
                ('problem', models.TextField(help_text='填写此图片的问题详情，必须是markdown格式', verbose_name='问题内容')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='suggestion_task', to='aidsp.Task', to_field='task_name', verbose_name='任务')),
            ],
        ),
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_content', models.TextField(help_text='填写问题的内容，必须是markdown格式', verbose_name='问题内容')),
                ('q_label', models.CharField(max_length=50, verbose_name='问题标签')),
                ('q_create_time', models.DateTimeField(verbose_name='问题创建时间')),
                ('answer_content', models.TextField(help_text='填写答案的内容，必须是markdown格式', verbose_name='答案内容')),
                ('a_create_time', models.DateTimeField(verbose_name='答案创建时间')),
                ('a_approval', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_a_approval', to='aidsp.User', to_field='name', verbose_name='问题点赞人')),
                ('a_author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_a_author', to='aidsp.User', to_field='name', verbose_name='答案作者')),
                ('documents', models.ManyToManyField(related_name='QA_project', to='aidsp.Document', verbose_name='文档')),
                ('q_author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_q_author', to='aidsp.User', to_field='name', verbose_name='问题作者')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='users_attend',
            field=models.ManyToManyField(related_name='users_attend', to='aidsp.User', verbose_name='参与人'),
        ),
        migrations.AddField(
            model_name='project',
            name='users_found',
            field=models.ManyToManyField(related_name='users_found', to='aidsp.User', verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='project',
            name='users_manager',
            field=models.ManyToManyField(related_name='users_manager', to='aidsp.User', verbose_name='管理人'),
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('performance', models.CharField(max_length=10, verbose_name='绩效')),
                ('date', models.DateField(verbose_name='打分日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_performance', to='aidsp.User', to_field='name', verbose_name='姓名')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_document', to='aidsp.User', to_field='name', verbose_name='姓名'),
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='数据集名称')),
                ('describe', models.CharField(max_length=200, verbose_name='数据集描述')),
                ('quantity_detials', models.CharField(max_length=200, verbose_name='数量详情')),
                ('path', models.CharField(max_length=200, verbose_name='存储路径')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_dataset', to='aidsp.Project', to_field='project_id', verbose_name='所属项目')),
            ],
        ),
    ]
