# Generated by Django 3.0.2 on 2020-02-04 09:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 2, 4, 9, 2, 28, 184059, tzinfo=utc), verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 4, 9, 9, 50, 571070, tzinfo=utc), verbose_name='更新时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestion',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 2, 4, 9, 10, 3, 303612, tzinfo=utc), verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestion',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 4, 9, 10, 7, 517695, tzinfo=utc), verbose_name='更新时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='打分日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='qa',
            name='q_create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='问题创建时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
