# Generated by Django 2.2.7 on 2020-03-06 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_dataset', to='aidsp.Project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=50, verbose_name='项目id'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_task', to='aidsp.Project', verbose_name='所属项目'),
        ),
    ]
