# Generated by Django 2.2.7 on 2020-03-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
