# Generated by Django 2.2.7 on 2020-04-15 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='tasks',
            field=models.ForeignKey(default='aaa', on_delete=django.db.models.deletion.DO_NOTHING, to='aidsp.Task', to_field='task_name', verbose_name='所属任务'),
            preserve_default=False,
        ),
    ]
