# Generated by Django 2.2.7 on 2020-06-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0002_task_current_workload'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='error_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='未通过理由'),
        ),
    ]
