# Generated by Django 2.2.7 on 2020-03-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0002_auto_20200316_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='img',
            field=models.CharField(default='dd', max_length=200, verbose_name='略缩图'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
    ]
