# Generated by Django 2.2.7 on 2020-04-24 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0002_img_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='tasks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidsp.Task', to_field='task_name', verbose_name='所属任务'),
        ),
    ]
