# Generated by Django 2.2.7 on 2020-03-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0002_auto_20200331_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='expected_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='quantity_week',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_description',
        ),
        migrations.AddField(
            model_name='project',
            name='expected_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预计完成时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='quantity_week',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='本周工作量'),
        ),
        migrations.AddField(
            model_name='project',
            name='task_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='任务描述'),
        ),
    ]
