# Generated by Django 2.2.7 on 2020-07-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0003_task_error_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='basic_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='基础量'),
        ),
        migrations.AddField(
            model_name='project',
            name='task_standard',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='任务标准'),
        ),
    ]
