# Generated by Django 2.2.7 on 2020-03-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0003_auto_20200317_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='describe',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='数据集描述'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='img',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='略缩图'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='存储路径'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='quantity_detials',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='数量详情'),
        ),
    ]
