# Generated by Django 2.2.7 on 2020-03-18 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0004_auto_20200318_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_dataset', to='aidsp.Project', verbose_name='所属项目'),
        ),
    ]
