# Generated by Django 2.2.7 on 2020-08-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0004_auto_20200710_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='current_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='实时点数'),
        ),
    ]
