# Generated by Django 2.2.7 on 2020-04-27 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0004_auto_20200424_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='labels', to='aidsp.Label', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='project',
            name='users_attend',
            field=models.ManyToManyField(blank=True, related_name='users_attend', to=settings.AUTH_USER_MODEL, verbose_name='参与人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='users_found',
            field=models.ManyToManyField(blank=True, related_name='users_found', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='users_manager',
            field=models.ManyToManyField(blank=True, related_name='users_manager', to=settings.AUTH_USER_MODEL, verbose_name='管理人'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ManyToManyField(blank=True, related_name='assignee_task', to=settings.AUTH_USER_MODEL, verbose_name='标注员'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reviewer',
            field=models.ManyToManyField(blank=True, related_name='reviewer_task', to=settings.AUTH_USER_MODEL, verbose_name='审核员'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_link',
            field=models.TextField(verbose_name='任务链接'),
        ),
    ]
