# Generated by Django 2.2.7 on 2020-03-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0004_auto_20200303_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.IntegerField(auto_created=True, blank=True, null=True, unique=True, verbose_name='项目id'),
        ),
    ]
