# Generated by Django 2.2.7 on 2020-10-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0005_task_current_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgBase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_name', models.CharField(max_length=100, verbose_name='图片名称')),
                ('dataset', models.CharField(max_length=20, verbose_name='所属数据集名称')),
                ('img_path', models.CharField(max_length=200, verbose_name='图片路径')),
                ('img_info', models.TextField(verbose_name='标注信息')),
                ('assignee', models.CharField(blank=True, max_length=10, null=True, verbose_name='标注员')),
                ('reviewer', models.CharField(blank=True, max_length=10, null=True, verbose_name='审核员')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
            ],
        ),
    ]
