# Generated by Django 2.2.7 on 2020-03-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0005_auto_20200318_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='img',
            field=models.TextField(blank=True, null=True, verbose_name='略缩图'),
        ),
    ]
