# Generated by Django 2.2.7 on 2020-11-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0006_imgbase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(max_length=50, verbose_name='数据集名称'),
        ),
        migrations.AlterField(
            model_name='imgbase',
            name='dataset',
            field=models.CharField(max_length=50, verbose_name='所属数据集名称'),
        ),
    ]
