# Generated by Django 2.2.7 on 2020-03-24 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0006_auto_20200318_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignee_task', to=settings.AUTH_USER_MODEL, to_field='name', verbose_name='标注员'),
        ),
        migrations.AlterField(
            model_name='task',
            name='begin_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='done_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='gross',
            field=models.IntegerField(blank=True, null=True, verbose_name='此任务工作总量'),
        ),
        migrations.AlterField(
            model_name='task',
            name='number_of_reviews',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='审核次数'),
        ),
        migrations.AlterField(
            model_name='task',
            name='quantity_available',
            field=models.IntegerField(blank=True, null=True, verbose_name='此任务有效工作量'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewer_task', to=settings.AUTH_USER_MODEL, to_field='name', verbose_name='审核员'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_label',
            field=models.DateTimeField(blank=True, null=True, verbose_name='时间标记点'),
        ),
        migrations.AlterField(
            model_name='task',
            name='total_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='任务历时'),
        ),
        migrations.AlterField(
            model_name='task',
            name='used_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='任务用时'),
        ),
    ]
