# Generated by Django 2.2.7 on 2020-03-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0007_auto_20200324_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='belong_task',
            field=models.CharField(default='sdf', max_length=20, verbose_name='所属大任务'),
            preserve_default=False,
        ),
    ]
