# Generated by Django 2.2.7 on 2020-12-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0007_auto_20201127_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duibi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_name', models.CharField(max_length=100, verbose_name='图片名称')),
                ('assignee', models.CharField(max_length=10, null=True, verbose_name='对比员')),
                ('duibi_res', models.CharField(max_length=10, null=True, verbose_name='对比结果')),
            ],
        ),
    ]
