# Generated by Django 2.2.7 on 2020-03-25 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0008_task_belong_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ManyToManyField(blank=True, null=True, related_name='assignee_task', to=settings.AUTH_USER_MODEL, verbose_name='标注员'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='task',
            name='reviewer',
            field=models.ManyToManyField(blank=True, null=True, related_name='reviewer_task', to=settings.AUTH_USER_MODEL, verbose_name='审核员'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_label',
            field=models.DateTimeField(blank=True, null=True, verbose_name='已用时间'),
        ),
    ]
