# Generated by Django 2.2.7 on 2020-03-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0009_auto_20200325_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未开始'), (1, '正在进行'), (2, '完成'), (3, '通过'), (4, '未通过'), (5, '暂停')], verbose_name='状态'),
        ),
    ]
