# Generated by Django 2.2.7 on 2020-12-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0010_auto_20201224_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgBase',
        ),
    ]
