# Generated by Django 2.2.7 on 2020-03-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0011_auto_20200325_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='total_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='任务历时'),
        ),
        migrations.AlterField(
            model_name='task',
            name='used_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='任务用时'),
        ),
    ]
