# Generated by Django 2.2.7 on 2020-03-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0012_auto_20200325_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='total_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='任务历时'),
        ),
        migrations.AlterField(
            model_name='task',
            name='used_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='任务用时'),
        ),
    ]
