# Generated by Django 2.2.7 on 2020-12-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0012_imgbase'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgbase',
            name='size',
            field=models.CharField(default='abc', max_length=15, verbose_name='图片尺寸'),
        ),
    ]
