# Generated by Django 2.2.7 on 2020-03-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0013_auto_20200325_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '采集任务'), (2, '标注任务')], default='1', verbose_name='任务类型'),
            preserve_default=False,
        ),
    ]
