# Generated by Django 2.2.7 on 2020-03-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidsp', '0014_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未开始'), (1, '正在进行'), (2, '待审核'), (3, '通过'), (4, '未通过'), (5, '暂停')], verbose_name='状态'),
        ),
    ]
